### ISSUE TITLE
Add GCN embedding model

### ISSUE THREAD

**Issue by hzahera** [dice-group/DAIKIRI-Embedding#20]
Hi Demir, 

It would be interesting if we could include GCN-align embedding model into the DAIKIRI-embedding library.  The reference model for GCN can be found here
https://github.com/nju-websoft/OpenEA/blob/master/src/openea/approaches/gcn_align.py 

Thanks, 
H.Z

**Comment by Demirrr** [comment]
Hello @hzahera ,

I was looking at the code in the provided link. Unfotunately, I was not able to understand few parts. The GCN-align model is defined in [here right](https://github.com/nju-websoft/OpenEA/blob/eda4e200ebec92f322a32efe9411c1bc6425fccf/src/openea/approaches/gcn_align.py#L677)? If yes, Would you please provide a link for the paper where this model is introduced ?

According to my understanding, this model is based on two neural models each of which has  two graph convolutional layers and none of these models directly tackle the link prediction task, e.g., (s,p,?). Is this correct ?

**Comment by Demirrr** [comment]
Thank you @hzahera for the clarification 
> There are two GCN network that learns structural+attribute(optional) embeddings for each node, then minimize shared loss to allocate similar entities close to each other in the semantic space. This is a supervised learning approach for entity-alignment. The task is to predict either 1 (two entities are aligned) or 0, no link prediction


Given that this model does not perform link prediction, it is not clear to me how to include it in our framework. Currently, we train approaches via three standard training strategies that are designed for the link precition. Consequently, it is unfortunately not clear to me how to add KGE models that are not designed towards the link prediction.

That being said, if you have time and interested, please make the pull request :)
