### ISSUE TITLE
KG Embeddings for Lymphography Dataset

### ISSUE THREAD

**Issue by hzahera** [dice-group/DAIKIRI-Embedding#21]
Hi @Demirrr , 

Currently, we are testing the DAIKIRI pipeline with Lymphography dataset, I would like to ask for Its KG embeddings, since I need for the DAIKIRI semantification work package. 

Original data can be found here:
ftp://daikiri@hobbitdata.informatik.uni-leipzig.de/Pipeline/KGConversion/lymphograph-raw.csv

Thanks,
Hamada

**Comment by Demirrr** [comment]
1. [Vectograph](https://github.com/dice-group/vectograph) applied to obtain a knowledge graph from a tabular data.
2. QMult is applied to learn embeddings of entities and relations.
