### ISSUE TITLE
Generated Embeddings..

### ISSUE THREAD

**Issue by hzahera** [dice-group/DAIKIRI-Embedding#9]
Hi, 

I have a question about the generated embeddings in the output file `QMult_entity_embeddings.csv`. The index column (0) has some values e.g. ` 0_quantile_9, 2_quantile_9` etc. I wonder, are these values related to the events e.g., `Event_0` or represent a new entity? 

Thanks,

**Comment by Demirrr** [comment]
Hello @hzahera 

I reckon there are several things are mixed up here. The title of this issue and its content appear to mismatch. 

That being said, I would like to summaries the steps and attempt to answer your question as follows:

1. Given a knowledge graph, QMult learns a vector representation for each entitiy and a relation as described in [here](https://arxiv.org/abs/2106.15230). 
2. If desired, these embeddings are stored in two seperate csv files, e.g. `QMult_entity_embeddings.csv` and `QMult_relation_embeddings.csv`.
3. An embedding csv file stores entities/relations as the index and learned vector representations as the value/data (see [pandas.DataFrame](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html)). 
4. If the index of `QMult_entity_embeddings.csv` contains ` 0_quantile_9, 2_quantile_9`, then this implies that ` 0_quantile_9, 2_quantile_9` are entities in the input KG. You could easily double check this. 

This issue appears to be more related to [the vectograph framework](https://github.com/dice-group/vectograph). Therein, I will provide a more detailed information as soon as possible.

**Comment by Demirrr** [comment]
@hzahera you may find [this explanation](https://github.com/dice-group/vectograph#creating-structured-data-from-tabular-data) helpful.

**Comment by hzahera** [comment]
Thanks @Demirrr for your clarification.
